# Lazygit Configuration
# TUI for git commands
# Catppuccin Frappe theme

gui:
  # Catppuccin Frappe color theme
  theme:
    activeBorderColor:
      - "#ca9ee6"  # mauve
      - bold
    inactiveBorderColor:
      - "#737994"  # overlay0
    optionsTextColor:
      - "#8caaee"  # blue
    selectedLineBgColor:
      - "#414559"  # surface0
    selectedRangeBgColor:
      - "#51576d"  # surface1
    cherryPickedCommitBgColor:
      - "#85c1dc"  # sapphire
    cherryPickedCommitFgColor:
      - "#8caaee"  # blue
    unstagedChangesColor:
      - "#e78284"  # red
    defaultFgColor:
      - "#c6d0f5"  # text
    searchingActiveBorderColor:
      - "#e5c890"  # yellow

  # UI settings
  showFileTree: true
  showListFooter: true
  showRandomTip: true
  showBranchCommitHash: true
  showBottomLine: true
  showCommandLog: true
  showIcons: true
  nerdFontsVersion: "3"
  commitLength:
    show: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible"
  language: "auto"
  timeFormat: "02 Jan 06"
  shortTimeFormat: "3:04PM"

  # Border style
  border: "rounded"

  # Window size
  windowSize: "normal"

  # Show divergence from base branch
  showDivergenceFromBaseBranch: "arrowAndNumber"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme=Catppuccin-frappe
    useConfig: false

  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  merging:
    manualCommit: false
    args: ""

  log:
    order: "topo-order"
    showGraph: "always"
    showWholeGraph: false

  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: true
  diffContextSize: 3

update:
  method: never

refresher:
  refreshInterval: 10
  fetchInterval: 60

confirmOnQuit: false

notARepository: "prompt"

promptToReturnFromSubprocess: true

keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItem-alt: "k"
    nextItem-alt: "j"
    prevPage: ","
    nextPage: "."
    gotoTop: "<"
    gotoBottom: ">"
    scrollLeft: "H"
    scrollRight: "L"
    prevBlock: "<left>"
    nextBlock: "<right>"
    prevBlock-alt: "h"
    nextBlock-alt: "l"
    jumpToBlock: ["1", "2", "3", "4", "5"]
    nextMatch: "n"
    prevMatch: "N"
    optionMenu: "x"
    optionMenu-alt1: "?"
    select: "<space>"
    goInto: "<enter>"
    openRecentRepos: "<c-r>"
    confirm: "<enter>"
    confirm-alt1: "y"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdown>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    scrollUpMain-alt2: "<c-u>"
    scrollDownMain-alt2: "<c-d>"
    executeCustomCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "]"
    prevTab: "["
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: "<c-s>"
    diffingMenu: "W"
    diffingMenu-alt: "<c-e>"
    copyToClipboard: "<c-o>"
    submitEditorText: "<enter>"
    extrasMenu: "@"
    toggleWhitespaceInDiffView: "<c-w>"
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"

  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"

  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
    openMergeTool: "M"
    openStatusFilter: "<c-b>"

  branches:
    createPullRequest: "o"
    viewPullRequestOptions: "O"
    checkoutBranchByName: "c"
    forceCheckoutBranch: "F"
    rebaseBranch: "r"
    renameBranch: "R"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    createTag: "T"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"

  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "c"
    cherryPickCopyRange: "C"
    pasteCommits: "v"
    tagCommit: "T"
    checkoutCommit: "<space>"
    resetCherryPick: "<c-R>"
    copyCommitMessageToClipboard: "<c-y>"
    openLogMenu: "<c-l>"
    viewBisectOptions: "b"

  stash:
    popStash: "g"
    renameStash: "r"

  commitFiles:
    checkoutCommitFile: "c"

  main:
    toggleDragSelect: "v"
    toggleDragSelect-alt: "V"
    toggleSelectHunk: "a"
    pickBothHunks: "b"

  submodules:
    init: "i"
    update: "u"
    bulkMenu: "b"

customCommands: []

os:
  editPreset: "nvim"
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  open: "xdg-open {{filename}} >/dev/null"
  openLink: "xdg-open {{link}} >/dev/null"
